# Generated by Django 4.1.3 on 2022-12-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('look', '0002_product_remove_userplus_facebook_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
